services:
  server:
    build: .
    command: python server.py
    volumes:
      # Useful for development
      - .:/usr/src/app
    environment:
      - DATA_HOST=data
    depends_on:
      - data
    ports:
      - "8080:8080"

  data:
    build: .
    volumes:
      # Useful for development
      - .:/usr/src/app
    command: python helpers/data.py
